# Generated by Django 4.2.3 on 2023-07-23 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='state',
        ),
    ]
